### ISSUE TITLE
Incorrect timestamp for 'time'

### ISSUE THREAD

**Issue by paulfouquet** [linz/python-linz-logger#89]
The following code:
https://github.com/linz/python-linz-logger/blob/d332d79b6ce7e46f352bd7063d705b32798a6211/linz_logger/logger.py#L67
returns an incorrect timestamp. If you convert this `timestamp` into a `date`, the time does not match with the current time.

**Comment by l0b0** [comment]
As discussed, this is because `datetime.utcnow()` returns a `datetime` without a time zone, so `.timestamp()` does the time zone offset *again,* resulting in a double offset.
